### ISSUE TITLE
Include URL rewriting support in nginx config

### ISSUE THREAD

**Issue by SenorSmartyPants** [linuxserver/docker-cops#31]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

When editing config_local.php to enable url writing, it should not generate a 404 error when attempting to download.
`    $config['cops_use_url_rewriting'] = "1";`

NGINX config is listed here
https://github.com/seblucas/cops/wiki/Url-Rewriting-with-COPS

## Current Behavior

404 error is generated for all /download or /view urls

## Steps to Reproduce

1. edit config_local.php to include `    $config['cops_use_url_rewriting'] = "1";`
2. navigate to book using COPS server.
3. Click download, or folder buttons
4. get 404 error

## Environment
**OS:** Armbian
**CPU architecture:** arm64
**How docker service was installed:** from the distro repo, using armbian-setup

## Command used to create docker container (run/create/compose/screenshot)

```
  cops:
    image: linuxserver/cops
    container_name: cops
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=100
    volumes:
      - /opt/appdata/cops:/config
      - /mnt/storage/media/Books:/books
    ports:
      - 9090:80
    restart: unless-stopped
```
