### ISSUE TITLE
[BUG] local.php file permissions incorrect 

### ISSUE THREAD

**Issue by nopoz** [linuxserver/docker-cops#58]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Getting the error when loading up a default instance of cops using 3.1.2-ls223 (latest as of writing)

```
Error loading local.php
Failed opening required '/app/www/public/config/local.php' (include_path='.:/usr/share/php83') in /app/www/public/config/config.php line 15
```

Checking the file permissions on `/app/www/public/config/local.php` it's owned by root and the permissions are `rwx` for root user only. Since the app runs with the user and group `abc`, the file cannot be read:

```
~#/docker exec -t -i cops /bin/bash
root@d790c89eb80f:/# cd /app/www/public/config
root@d790c89eb80f:/app/www/public/config# ls -la
total 48
drwxrwxr-x 1 root root   150 Sep 10 15:28 .
drwxr-xr-x 1 root root  1128 Sep  9 10:36 ..
-rw-rw-r-- 1 root root    22 Sep  9 05:11 .gitignore
-rw-rw-r-- 1 root root  1857 Sep  9 05:11 config.php
-rw-rw-r-- 1 root root 21928 Sep  9 05:11 default.php
-rw-rw-r-- 1 root root  2445 Sep  9 05:11 loader.php
-rwx------ 1 root root  3993 Sep 10 15:28 local.php
-rw-rw-r-- 1 root root  2476 Sep  9 05:11 local.php.example
-rw-rw-r-- 1 root root   679 Sep  9 05:11 test.php
```

Changing the permissions to match the other files in the directory with `chmod 664 local.php`, the error goes away and cops loads as expected in the browser. 

Compose file used:

```
services:
    cops:
        container_name: cops
        environment:
            - PUID=666
            - PGID=1337
            - TZ=America/Los_Angeles
        ports:
            - '127.0.0.1:5230:80'
        volumes:
            - '/docker/cops:/config'
            - '/ebooks:/books'
        restart: unless-stopped
        image: lscr.io/linuxserver/cops:version-3.1.2-ls223
 ```

### Expected Behavior

Cops should load correctly. 

### Steps To Reproduce

Just run the container from scratch with the above compose file. 

### Environment

```markdown
- OS: n/a
- How docker service was installed: portainer stack/docker compose
```

### CPU architecture

x86-64

### Docker creation

```bash
services:
    cops:
        container_name: cops
        environment:
            - PUID=666
            - PGID=1337
            - TZ=America/Los_Angeles
        ports:
            - '127.0.0.1:5230:80'
        volumes:
            - '/docker/cops:/config'
            - '/ebooks:/books'
        restart: unless-stopped
        image: lscr.io/linuxserver/cops:version-3.1.2-ls223
```

### Container logs

```bash
n/a
```

**Comment by nopoz** [comment]
You can workaround this issue by running this [custom-cont-init.d](https://docs.linuxserver.io/general/container-customization/#custom-scripts) script at startup:

```bash
#!/usr/bin/env bash

# script to fix file permissions see https://github.com/linuxserver/docker-cops/issues/58

file="/app/www/public/config/local.php"

check_perm(){
	perm=$(stat -c "%a" "$file")
}

check_perm

if [[ "$perm" -eq 664 ]]; then
	echo "Permissions on $file are correct."
else
	echo "Permissions on file are incorrect."
	echo "Current permissions are: $perm"
	echo "Changing to: 644"
	chmod 664 $file
	check_perm
	echo "File permissions are now: $perm"
fi
```

**Comment by mikespub** [comment]
Hi @nopoz 

is it possible you started with an existing file config_local.php with permissions -rwx------ in your local /docker/cops directory?

Because to help migration from older versions the current [init-cops-config/run](https://github.com/linuxserver/docker-cops/blob/master/root/etc/s6-overlay/s6-rc.d/init-cops-config/run) script will copy that to /config/config/local.php instead of using a new /defaults/config/local.php

When I try to install from scratch with an empty local /tmp/config and

```
        volumes:
            - /tmp/config:/config
```

I end up with a local.php file with permission 644 for my defined user locally, and for root inside the container, which is correct.

**Comment by nopoz** [comment]
Hi @mikespub I redid everything from scratch to sanity check my previous testing - no old config directory or anything. I get the same error:

```
Error loading local.php
Failed opening required '/app/www/public/config/local.php' (include_path='.:/usr/share/php83') in /app/www/public/config/config.php line 15
```
Checking the file permissions of `/app/www/public/config/local.php` inside the new container - they are the same as in the previous test:

```
# docker exec -t -i cops-test /bin/bash
root@1e1a373f1b85:/# ls -la /app/www/public/config/local.php
-rwx------ 1 root root 3993 Sep 12 12:16 /app/www/public/config/local.php
```

Checking the local.php file in the config directory as you mention, these are the permissions:

```
# ls -la /docker/cops-test/config/local.php
-rwx------ 1 cops ebooks 3993 Sep 12 12:14 /docker/cops-test/config/local.php
```

Compose file:

```yaml
services:
    cops-test:
        container_name: cops-test
        environment:
            - PUID=666 # cops
            - PGID=1337 # ebooks
        ports:
            - 5231:80
        volumes:
            - /docker/cops-test:/config
            - /ebooks:/books
        restart: unless-stopped
        image: lscr.io/linuxserver/cops:3.1.2-ls223
```
